/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.stockmaster.main.panel;

import com.stockmaster.assets.components.jDialogs.PasswordSpecialAccess;

/**
 *
 * @author User
 */
public class profilePage extends javax.swing.JPanel {

    /**
     * Creates new form productManagement
     */
    public profilePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        profilePanel1 = new com.stockmaster.assets.components.ProfilePanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imageLabel1 = new com.stockmaster.assets.components.imageLabel();
        background11 = new com.stockmaster.assets.components.Background1();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        profilePanel2 = new com.stockmaster.assets.components.ProfilePanel();
        jLabel9 = new javax.swing.JLabel();
        spicyTextField11 = new com.stockmaster.assets.components.SMTextField1();
        jLabel10 = new javax.swing.JLabel();
        spicyTextField12 = new com.stockmaster.assets.components.SMTextField1();
        jLabel11 = new javax.swing.JLabel();
        spicyTextField13 = new com.stockmaster.assets.components.SMTextField1();
        spicyTextField14 = new com.stockmaster.assets.components.SMTextField1();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spicyTextField15 = new com.stockmaster.assets.components.SMTextField1();
        jLabel14 = new javax.swing.JLabel();
        sMButton21 = new com.stockmaster.assets.components.SMButton2();
        sMPassword1 = new com.stockmaster.components.SMPassword();
        jLabel15 = new javax.swing.JLabel();
        spicyTextField16 = new com.stockmaster.assets.components.SMTextField1();
        spicyTextField17 = new com.stockmaster.assets.components.SMTextField1();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1175, 756));

        profilePanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(98, 98, 98));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin");

        jLabel1.setFont(new java.awt.Font("Inter ExtraBold", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sinura Wahalathanthri");

        imageLabel1.setText("imageLabel1");
        imageLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageLabel1ActionPerformed(evt);
            }
        });

        background11.setBackground(new java.awt.Color(244, 252, 255));

        jLabel3.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel3.setText("This Months Salary :");

        jLabel4.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel4.setText("This Months Bonus :");

        jLabel5.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel5.setText("Number of days worked :");

        jLabel6.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 117, 255));
        jLabel6.setText("isPaid");

        jLabel7.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 117, 255));
        jLabel7.setText("Rs.1520.00");

        jLabel8.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 117, 255));
        jLabel8.setText("26");

        javax.swing.GroupLayout background11Layout = new javax.swing.GroupLayout(background11);
        background11.setLayout(background11Layout);
        background11Layout.setHorizontalGroup(
            background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background11Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(background11Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(background11Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        background11Layout.setVerticalGroup(
            background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout profilePanel1Layout = new javax.swing.GroupLayout(profilePanel1);
        profilePanel1.setLayout(profilePanel1Layout);
        profilePanel1Layout.setHorizontalGroup(
            profilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(profilePanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(background11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        profilePanel1Layout.setVerticalGroup(
            profilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(background11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profilePanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(80, 80, 80));
        jLabel9.setText("First Name");

        spicyTextField11.setText("spicyTextField11");
        spicyTextField11.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(80, 80, 80));
        jLabel10.setText("Last Name");

        spicyTextField12.setText("spicyTextField11");
        spicyTextField12.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(80, 80, 80));
        jLabel11.setText("Email");

        spicyTextField13.setText("spicyTextField13");
        spicyTextField13.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        spicyTextField14.setText("spicyTextField13");
        spicyTextField14.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(80, 80, 80));
        jLabel12.setText("Mobile");

        jLabel13.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(80, 80, 80));
        jLabel13.setText("Username");

        spicyTextField15.setText("spicyTextField15");
        spicyTextField15.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(80, 80, 80));
        jLabel14.setText("Password");

        sMButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/lock-alt.png"))); // NOI18N
        sMButton21.setContentAreaFilled(false);
        sMButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMButton21ActionPerformed(evt);
            }
        });

        sMPassword1.setText("sMPassword1");
        sMPassword1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(80, 80, 80));
        jLabel15.setText("Joined Date");

        spicyTextField16.setText("spicyTextField16");
        spicyTextField16.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        spicyTextField17.setText("spicyTextField16");
        spicyTextField17.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(80, 80, 80));
        jLabel16.setText("No. Day Worked Since Joined");

        jButton1.setBackground(new java.awt.Color(0, 133, 255));
        jButton1.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save Information");

        javax.swing.GroupLayout profilePanel2Layout = new javax.swing.GroupLayout(profilePanel2);
        profilePanel2.setLayout(profilePanel2Layout);
        profilePanel2Layout.setHorizontalGroup(
            profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profilePanel2Layout.createSequentialGroup()
                        .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilePanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(profilePanel2Layout.createSequentialGroup()
                                .addComponent(spicyTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(spicyTextField17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profilePanel2Layout.createSequentialGroup()
                        .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spicyTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spicyTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profilePanel2Layout.createSequentialGroup()
                        .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spicyTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(profilePanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(84, 84, 84)))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spicyTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(profilePanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(76, 76, 76))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profilePanel2Layout.createSequentialGroup()
                        .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spicyTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilePanel2Layout.createSequentialGroup()
                                .addComponent(sMPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sMButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(44, 44, 44))
        );
        profilePanel2Layout.setVerticalGroup(
            profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profilePanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spicyTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spicyTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spicyTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spicyTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sMButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spicyTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sMPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(profilePanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profilePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spicyTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spicyTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profilePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profilePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sMButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMButton21ActionPerformed
       
    }//GEN-LAST:event_sMButton21ActionPerformed

    private void imageLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageLabel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageLabel1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.stockmaster.assets.components.Background1 background11;
    private com.stockmaster.assets.components.imageLabel imageLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.stockmaster.assets.components.ProfilePanel profilePanel1;
    private com.stockmaster.assets.components.ProfilePanel profilePanel2;
    private com.stockmaster.assets.components.SMButton2 sMButton21;
    private com.stockmaster.components.SMPassword sMPassword1;
    private com.stockmaster.assets.components.SMTextField1 spicyTextField11;
    private com.stockmaster.assets.components.SMTextField1 spicyTextField12;
    private com.stockmaster.assets.components.SMTextField1 spicyTextField13;
    private com.stockmaster.assets.components.SMTextField1 spicyTextField14;
    private com.stockmaster.assets.components.SMTextField1 spicyTextField15;
    private com.stockmaster.assets.components.SMTextField1 spicyTextField16;
    private com.stockmaster.assets.components.SMTextField1 spicyTextField17;
    // End of variables declaration//GEN-END:variables
}
