/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.stockmaster.main;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.stockmaster.main.panel.CompanyRegistration;
import com.stockmaster.main.panel.GoodRecievedNotes;
import com.stockmaster.main.panel.Home;
import com.stockmaster.main.panel.ManageUsers;
import com.stockmaster.main.panel.ManageProducts;
import com.stockmaster.main.panel.ManageStock;
import com.stockmaster.main.panel.StockCheck;
import com.stockmaster.main.panel.StockManagement;
import com.stockmaster.main.panel.Test;
import com.stockmaster.main.panel.brandnCategoryManagement;
import com.stockmaster.main.panel.profilePage;
import java.awt.Color;
import java.time.LocalDate;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SinuraWahalathanthri
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */

    public Dashboard() {
        initComponents();
          loadPanel(new Home());
    }

    private void loadPanel(JPanel panel) {
        contentLoader.removeAll();
        if (!panel.isShowing()) {
            contentLoader.add(panel);
            FlatLaf.updateUI();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        ManageProductsPanel = new javax.swing.JPanel();
        ManageProducts = new javax.swing.JButton();
        HomePanel = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        ManageUsersPanel = new javax.swing.JPanel();
        ManageUsers = new javax.swing.JButton();
        ManageCategoriesPanel = new javax.swing.JPanel();
        ManageCategories = new javax.swing.JButton();
        StockManagmentPanel = new javax.swing.JPanel();
        StockManagment = new javax.swing.JButton();
        GoodsRecivedNotePanel = new javax.swing.JPanel();
        GoodsRecivedNote = new javax.swing.JButton();
        GoodsReturnNotePanel = new javax.swing.JPanel();
        GoodsReturnNote = new javax.swing.JButton();
        SalaryManagmentPanel = new javax.swing.JPanel();
        SalaryManagment = new javax.swing.JButton();
        OrderPanel = new javax.swing.JPanel();
        Order = new javax.swing.JButton();
        CompanyRegPanel = new javax.swing.JPanel();
        CompanyReg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        background11 = new com.stockmaster.assets.components.Background1();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sMSearch1 = new com.stockmaster.assets.components.SMSearch();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sMButton11 = new com.stockmaster.assets.components.SMButton1();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentLoader = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Master Pro");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(40, 101, 155));

        jScrollPane1.setBackground(new java.awt.Color(40, 101, 155));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 101, 155)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(40, 101, 155));

        ManageProductsPanel.setBackground(new java.awt.Color(40, 101, 155));

        ManageProducts.setBackground(new java.awt.Color(40, 101, 155));
        ManageProducts.setForeground(new java.awt.Color(187, 189, 204));
        ManageProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/cube.png"))); // NOI18N
        ManageProducts.setText("Manage Products");
        ManageProducts.setBorder(null);
        ManageProducts.setContentAreaFilled(false);
        ManageProducts.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ManageProducts.setIconTextGap(8);
        ManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageProductsPanelLayout = new javax.swing.GroupLayout(ManageProductsPanel);
        ManageProductsPanel.setLayout(ManageProductsPanelLayout);
        ManageProductsPanelLayout.setHorizontalGroup(
            ManageProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageProductsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManageProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ManageProductsPanelLayout.setVerticalGroup(
            ManageProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageProductsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ManageProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        HomePanel.setBackground(new java.awt.Color(23, 91, 150));

        Home.setBackground(new java.awt.Color(23, 91, 150));
        Home.setForeground(new java.awt.Color(187, 189, 204));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/house-blank.png"))); // NOI18N
        Home.setText("Home");
        Home.setBorder(null);
        Home.setContentAreaFilled(false);
        Home.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Home.setIconTextGap(8);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ManageUsersPanel.setBackground(new java.awt.Color(40, 101, 155));

        ManageUsers.setBackground(new java.awt.Color(40, 101, 155));
        ManageUsers.setForeground(new java.awt.Color(187, 189, 204));
        ManageUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/mode-portrait.png"))); // NOI18N
        ManageUsers.setText("Manage Users");
        ManageUsers.setBorder(null);
        ManageUsers.setContentAreaFilled(false);
        ManageUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ManageUsers.setIconTextGap(8);
        ManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageUsersPanelLayout = new javax.swing.GroupLayout(ManageUsersPanel);
        ManageUsersPanel.setLayout(ManageUsersPanelLayout);
        ManageUsersPanelLayout.setHorizontalGroup(
            ManageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageUsersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManageUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ManageUsersPanelLayout.setVerticalGroup(
            ManageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageUsersPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ManageCategoriesPanel.setBackground(new java.awt.Color(40, 101, 155));

        ManageCategories.setBackground(new java.awt.Color(40, 101, 155));
        ManageCategories.setForeground(new java.awt.Color(187, 189, 204));
        ManageCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/category-alt.png"))); // NOI18N
        ManageCategories.setText("Manage Category & Brand");
        ManageCategories.setBorder(null);
        ManageCategories.setContentAreaFilled(false);
        ManageCategories.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ManageCategories.setIconTextGap(8);
        ManageCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCategoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageCategoriesPanelLayout = new javax.swing.GroupLayout(ManageCategoriesPanel);
        ManageCategoriesPanel.setLayout(ManageCategoriesPanelLayout);
        ManageCategoriesPanelLayout.setHorizontalGroup(
            ManageCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageCategoriesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManageCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
        );
        ManageCategoriesPanelLayout.setVerticalGroup(
            ManageCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageCategoriesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ManageCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        StockManagmentPanel.setBackground(new java.awt.Color(40, 101, 155));

        StockManagment.setBackground(new java.awt.Color(40, 101, 155));
        StockManagment.setForeground(new java.awt.Color(187, 189, 204));
        StockManagment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/supplier-alt (1).png"))); // NOI18N
        StockManagment.setText("Stock Management");
        StockManagment.setBorder(null);
        StockManagment.setContentAreaFilled(false);
        StockManagment.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        StockManagment.setIconTextGap(8);
        StockManagment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockManagmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StockManagmentPanelLayout = new javax.swing.GroupLayout(StockManagmentPanel);
        StockManagmentPanel.setLayout(StockManagmentPanelLayout);
        StockManagmentPanelLayout.setHorizontalGroup(
            StockManagmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockManagmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StockManagment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StockManagmentPanelLayout.setVerticalGroup(
            StockManagmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockManagmentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(StockManagment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        GoodsRecivedNotePanel.setBackground(new java.awt.Color(40, 101, 155));

        GoodsRecivedNote.setBackground(new java.awt.Color(40, 101, 155));
        GoodsRecivedNote.setForeground(new java.awt.Color(187, 189, 204));
        GoodsRecivedNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/memo-pad.png"))); // NOI18N
        GoodsRecivedNote.setText("Goods Receive Note");
        GoodsRecivedNote.setBorder(null);
        GoodsRecivedNote.setContentAreaFilled(false);
        GoodsRecivedNote.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        GoodsRecivedNote.setIconTextGap(8);
        GoodsRecivedNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoodsRecivedNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GoodsRecivedNotePanelLayout = new javax.swing.GroupLayout(GoodsRecivedNotePanel);
        GoodsRecivedNotePanel.setLayout(GoodsRecivedNotePanelLayout);
        GoodsRecivedNotePanelLayout.setHorizontalGroup(
            GoodsRecivedNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GoodsRecivedNotePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GoodsRecivedNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GoodsRecivedNotePanelLayout.setVerticalGroup(
            GoodsRecivedNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GoodsRecivedNotePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(GoodsRecivedNote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        GoodsReturnNotePanel.setBackground(new java.awt.Color(40, 101, 155));

        GoodsReturnNote.setBackground(new java.awt.Color(40, 101, 155));
        GoodsReturnNote.setForeground(new java.awt.Color(187, 189, 204));
        GoodsReturnNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/journal-alt.png"))); // NOI18N
        GoodsReturnNote.setText("Goods Return  Note");
        GoodsReturnNote.setBorder(null);
        GoodsReturnNote.setContentAreaFilled(false);
        GoodsReturnNote.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        GoodsReturnNote.setIconTextGap(8);
        GoodsReturnNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoodsReturnNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GoodsReturnNotePanelLayout = new javax.swing.GroupLayout(GoodsReturnNotePanel);
        GoodsReturnNotePanel.setLayout(GoodsReturnNotePanelLayout);
        GoodsReturnNotePanelLayout.setHorizontalGroup(
            GoodsReturnNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GoodsReturnNotePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GoodsReturnNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GoodsReturnNotePanelLayout.setVerticalGroup(
            GoodsReturnNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GoodsReturnNotePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(GoodsReturnNote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SalaryManagmentPanel.setBackground(new java.awt.Color(40, 101, 155));

        SalaryManagment.setBackground(new java.awt.Color(40, 101, 155));
        SalaryManagment.setForeground(new java.awt.Color(187, 189, 204));
        SalaryManagment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/piggy-bank_1.png"))); // NOI18N
        SalaryManagment.setText("Salary Management");
        SalaryManagment.setBorder(null);
        SalaryManagment.setContentAreaFilled(false);
        SalaryManagment.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        SalaryManagment.setIconTextGap(8);
        SalaryManagment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryManagmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SalaryManagmentPanelLayout = new javax.swing.GroupLayout(SalaryManagmentPanel);
        SalaryManagmentPanel.setLayout(SalaryManagmentPanelLayout);
        SalaryManagmentPanelLayout.setHorizontalGroup(
            SalaryManagmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalaryManagmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SalaryManagment, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
        );
        SalaryManagmentPanelLayout.setVerticalGroup(
            SalaryManagmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalaryManagmentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SalaryManagment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        OrderPanel.setBackground(new java.awt.Color(40, 101, 155));

        Order.setBackground(new java.awt.Color(40, 101, 155));
        Order.setForeground(new java.awt.Color(187, 189, 204));
        Order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/selling.png"))); // NOI18N
        Order.setText("Invoice");
        Order.setBorder(null);
        Order.setContentAreaFilled(false);
        Order.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Order.setIconTextGap(8);
        Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CompanyRegPanel.setBackground(new java.awt.Color(40, 101, 155));

        CompanyReg.setBackground(new java.awt.Color(40, 101, 155));
        CompanyReg.setForeground(new java.awt.Color(187, 189, 204));
        CompanyReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/building (1).png"))); // NOI18N
        CompanyReg.setText("Company & Branch Registrations");
        CompanyReg.setBorder(null);
        CompanyReg.setContentAreaFilled(false);
        CompanyReg.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        CompanyReg.setIconTextGap(8);
        CompanyReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CompanyRegPanelLayout = new javax.swing.GroupLayout(CompanyRegPanel);
        CompanyRegPanel.setLayout(CompanyRegPanelLayout);
        CompanyRegPanelLayout.setHorizontalGroup(
            CompanyRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompanyRegPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CompanyReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CompanyRegPanelLayout.setVerticalGroup(
            CompanyRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompanyRegPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CompanyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OrderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageProductsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageUsersPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageCategoriesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StockManagmentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GoodsRecivedNotePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GoodsReturnNotePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SalaryManagmentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(CompanyRegPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageProductsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageUsersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageCategoriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockManagmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoodsRecivedNotePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoodsReturnNotePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SalaryManagmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompanyRegPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jLabel5.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(192, 192, 192));
        jLabel5.setText("Today is 2024/07/03");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/img/StockMaster.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(192, 192, 192));
        jLabel3.setText("Master");

        jLabel2.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Stock");

        jLabel4.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pro");

        background11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel6.setText("Sinura Wahalathanthri");

        jLabel7.setFont(new java.awt.Font("Inter Medium", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(149, 149, 149));
        jLabel7.setText("ADMIN");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/sign-out-alt.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout background11Layout = new javax.swing.GroupLayout(background11);
        background11.setLayout(background11Layout);
        background11Layout.setHorizontalGroup(
            background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        background11Layout.setVerticalGroup(
            background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background11Layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background11Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel4))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(background11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(120, 120, 120));
        jLabel8.setText("Welcome Back to Stock Master Pro");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stockmaster/assets/icon/search.png"))); // NOI18N

        jTextField1.setBackground(new java.awt.Color(246, 246, 246));
        jTextField1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 246, 246)));

        javax.swing.GroupLayout sMSearch1Layout = new javax.swing.GroupLayout(sMSearch1);
        sMSearch1.setLayout(sMSearch1Layout);
        sMSearch1Layout.setHorizontalGroup(
            sMSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sMSearch1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        sMSearch1Layout.setVerticalGroup(
            sMSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(120, 120, 120));
        jLabel9.setText("Sinura Wahalathanthri");

        sMButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMButton11ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Stock Master Pro Powered By");

        jLabel12.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ceylon XZORA Software Solutions © ️All Rights Reserved 2024");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        contentLoader.setBackground(new java.awt.Color(255, 255, 255));
        contentLoader.setLayout(new java.awt.BorderLayout());
        jScrollPane2.setViewportView(contentLoader);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sMSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sMButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sMSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sMButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addComponent(jLabel12)
                .addGap(10, 10, 10))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        loadPanel(new Home());

        HomePanel.setBackground(new Color(23, 91, 150));
        Home.setBackground(new Color(23, 91, 150));

        OrderPanel.setBackground(new Color(40, 101, 155));
        Order.setBackground(new Color(40, 101, 155));
        ManageUsersPanel.setBackground(new Color(40, 101, 155));
        ManageUsers.setBackground(new Color(40, 101, 155));
        ManageProductsPanel.setBackground(new Color(40, 101, 155));
        ManageProducts.setBackground(new Color(40, 101, 155));
        ManageCategoriesPanel.setBackground(new Color(40, 101, 155));
        ManageCategories.setBackground(new Color(40, 101, 155));
        SalaryManagmentPanel.setBackground(new Color(40, 101, 155));
        SalaryManagment.setBackground(new Color(40, 101, 155));
        StockManagmentPanel.setBackground(new Color(40, 101, 155));
        StockManagment.setBackground(new Color(40, 101, 155));
        GoodsRecivedNotePanel.setBackground(new Color(40, 101, 155));
        GoodsRecivedNote.setBackground(new Color(40, 101, 155));
        GoodsReturnNotePanel.setBackground(new Color(40, 101, 155));
        GoodsReturnNote.setBackground(new Color(40, 101, 155));
        CompanyRegPanel.setBackground(new Color(40, 101, 155));
        CompanyReg.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_HomeActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        OrderPanel.setBackground(new Color(23, 91, 150));
        Order.setBackground(new Color(23, 91, 150));

        HomePanel.setBackground(new Color(40, 101, 155));
        Home.setBackground(new Color(40, 101, 155));
        ManageUsersPanel.setBackground(new Color(40, 101, 155));
        ManageUsers.setBackground(new Color(40, 101, 155));
        ManageProductsPanel.setBackground(new Color(40, 101, 155));
        ManageProducts.setBackground(new Color(40, 101, 155));
        ManageCategoriesPanel.setBackground(new Color(40, 101, 155));
        ManageCategories.setBackground(new Color(40, 101, 155));
        SalaryManagmentPanel.setBackground(new Color(40, 101, 155));
        SalaryManagment.setBackground(new Color(40, 101, 155));
        StockManagmentPanel.setBackground(new Color(40, 101, 155));
        StockManagment.setBackground(new Color(40, 101, 155));
        GoodsRecivedNotePanel.setBackground(new Color(40, 101, 155));
        GoodsRecivedNote.setBackground(new Color(40, 101, 155));
        GoodsReturnNotePanel.setBackground(new Color(40, 101, 155));
        GoodsReturnNote.setBackground(new Color(40, 101, 155));
        CompanyRegPanel.setBackground(new Color(40, 101, 155));
        CompanyReg.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_OrderActionPerformed

    private void ManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProductsActionPerformed
        loadPanel(new ManageProducts());

        ManageProducts.setBackground(new Color(23, 91, 150));
        ManageProductsPanel.setBackground(new Color(23, 91, 150));

        HomePanel.setBackground(new Color(40, 101, 155));
        Home.setBackground(new Color(40, 101, 155));
        ManageUsersPanel.setBackground(new Color(40, 101, 155));
        ManageUsers.setBackground(new Color(40, 101, 155));
        Order.setBackground(new Color(40, 101, 155));
        OrderPanel.setBackground(new Color(40, 101, 155));
        ManageCategoriesPanel.setBackground(new Color(40, 101, 155));
        ManageCategories.setBackground(new Color(40, 101, 155));
        SalaryManagmentPanel.setBackground(new Color(40, 101, 155));
        SalaryManagment.setBackground(new Color(40, 101, 155));
        StockManagmentPanel.setBackground(new Color(40, 101, 155));
        StockManagment.setBackground(new Color(40, 101, 155));
        GoodsRecivedNotePanel.setBackground(new Color(40, 101, 155));
        GoodsRecivedNote.setBackground(new Color(40, 101, 155));
        GoodsReturnNotePanel.setBackground(new Color(40, 101, 155));
        GoodsReturnNote.setBackground(new Color(40, 101, 155));
        CompanyRegPanel.setBackground(new Color(40, 101, 155));
        CompanyReg.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_ManageProductsActionPerformed

    private void ManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUsersActionPerformed
        loadPanel(new ManageUsers());
        
        ManageUsersPanel.setBackground(new Color(23, 91, 150));
        ManageUsers.setBackground(new Color(23, 91, 150));

        HomePanel.setBackground(new Color(40, 101, 155));
        Home.setBackground(new Color(40, 101, 155));
        ManageProductsPanel.setBackground(new Color(40, 101, 155));
        ManageProducts.setBackground(new Color(40, 101, 155));
        Order.setBackground(new Color(40, 101, 155));
        OrderPanel.setBackground(new Color(40, 101, 155));
        ManageCategoriesPanel.setBackground(new Color(40, 101, 155));
        ManageCategories.setBackground(new Color(40, 101, 155));
        SalaryManagmentPanel.setBackground(new Color(40, 101, 155));
        SalaryManagment.setBackground(new Color(40, 101, 155));
        StockManagmentPanel.setBackground(new Color(40, 101, 155));
        StockManagment.setBackground(new Color(40, 101, 155));
        GoodsRecivedNotePanel.setBackground(new Color(40, 101, 155));
        GoodsRecivedNote.setBackground(new Color(40, 101, 155));
        GoodsReturnNotePanel.setBackground(new Color(40, 101, 155));
        GoodsReturnNote.setBackground(new Color(40, 101, 155));
        CompanyRegPanel.setBackground(new Color(40, 101, 155));
        CompanyReg.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_ManageUsersActionPerformed

    private void ManageCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCategoriesActionPerformed
          loadPanel(new brandnCategoryManagement(this));

        ManageCategoriesPanel.setBackground(new Color(23, 91, 150));
        ManageCategories.setBackground(new Color(23, 91, 150));

        HomePanel.setBackground(new Color(40, 101, 155));
        Home.setBackground(new Color(40, 101, 155));
        ManageProductsPanel.setBackground(new Color(40, 101, 155));
        ManageProducts.setBackground(new Color(40, 101, 155));
        Order.setBackground(new Color(40, 101, 155));
        OrderPanel.setBackground(new Color(40, 101, 155));
        ManageUsersPanel.setBackground(new Color(40, 101, 155));
        ManageUsers.setBackground(new Color(40, 101, 155));
        SalaryManagmentPanel.setBackground(new Color(40, 101, 155));
        SalaryManagment.setBackground(new Color(40, 101, 155));
        StockManagmentPanel.setBackground(new Color(40, 101, 155));
        StockManagment.setBackground(new Color(40, 101, 155));
        GoodsRecivedNotePanel.setBackground(new Color(40, 101, 155));
        GoodsRecivedNote.setBackground(new Color(40, 101, 155));
        GoodsReturnNotePanel.setBackground(new Color(40, 101, 155));
        GoodsReturnNote.setBackground(new Color(40, 101, 155));
        CompanyRegPanel.setBackground(new Color(40, 101, 155));
        CompanyReg.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_ManageCategoriesActionPerformed

    private void StockManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockManagmentActionPerformed
        loadPanel(new StockManagement());

        StockManagmentPanel.setBackground(new Color(23, 91, 150));
        StockManagment.setBackground(new Color(23, 91, 150));

        HomePanel.setBackground(new Color(40, 101, 155));
        Home.setBackground(new Color(40, 101, 155));
        ManageProductsPanel.setBackground(new Color(40, 101, 155));
        ManageProducts.setBackground(new Color(40, 101, 155));
        Order.setBackground(new Color(40, 101, 155));
        OrderPanel.setBackground(new Color(40, 101, 155));
        ManageUsersPanel.setBackground(new Color(40, 101, 155));
        ManageUsers.setBackground(new Color(40, 101, 155));
        SalaryManagmentPanel.setBackground(new Color(40, 101, 155));
        SalaryManagment.setBackground(new Color(40, 101, 155));
        ManageCategoriesPanel.setBackground(new Color(40, 101, 155));
        ManageCategories.setBackground(new Color(40, 101, 155));
        GoodsRecivedNotePanel.setBackground(new Color(40, 101, 155));
        GoodsRecivedNote.setBackground(new Color(40, 101, 155));
        GoodsReturnNotePanel.setBackground(new Color(40, 101, 155));
        GoodsReturnNote.setBackground(new Color(40, 101, 155));
        CompanyRegPanel.setBackground(new Color(40, 101, 155));
        CompanyReg.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_StockManagmentActionPerformed

    private void GoodsRecivedNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoodsRecivedNoteActionPerformed
        loadPanel(new StockCheck(this));

        GoodsRecivedNotePanel.setBackground(new Color(23, 91, 150));
        GoodsRecivedNote.setBackground(new Color(23, 91, 150));

        HomePanel.setBackground(new Color(40, 101, 155));
        Home.setBackground(new Color(40, 101, 155));
        ManageProductsPanel.setBackground(new Color(40, 101, 155));
        ManageProducts.setBackground(new Color(40, 101, 155));
        Order.setBackground(new Color(40, 101, 155));
        OrderPanel.setBackground(new Color(40, 101, 155));
        ManageUsersPanel.setBackground(new Color(40, 101, 155));
        ManageUsers.setBackground(new Color(40, 101, 155));
        SalaryManagmentPanel.setBackground(new Color(40, 101, 155));
        SalaryManagment.setBackground(new Color(40, 101, 155));
        ManageCategoriesPanel.setBackground(new Color(40, 101, 155));
        ManageCategories.setBackground(new Color(40, 101, 155));
        StockManagmentPanel.setBackground(new Color(40, 101, 155));
        StockManagment.setBackground(new Color(40, 101, 155));
        GoodsReturnNotePanel.setBackground(new Color(40, 101, 155));
        GoodsReturnNote.setBackground(new Color(40, 101, 155));
        CompanyRegPanel.setBackground(new Color(40, 101, 155));
        CompanyReg.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_GoodsRecivedNoteActionPerformed

    private void GoodsReturnNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoodsReturnNoteActionPerformed
        GoodsReturnNotePanel.setBackground(new Color(23, 91, 150));
        GoodsReturnNote.setBackground(new Color(23, 91, 150));

        HomePanel.setBackground(new Color(40, 101, 155));
        Home.setBackground(new Color(40, 101, 155));
        ManageProductsPanel.setBackground(new Color(40, 101, 155));
        ManageProducts.setBackground(new Color(40, 101, 155));
        Order.setBackground(new Color(40, 101, 155));
        OrderPanel.setBackground(new Color(40, 101, 155));
        ManageUsersPanel.setBackground(new Color(40, 101, 155));
        ManageUsers.setBackground(new Color(40, 101, 155));
        SalaryManagmentPanel.setBackground(new Color(40, 101, 155));
        SalaryManagment.setBackground(new Color(40, 101, 155));
        ManageCategoriesPanel.setBackground(new Color(40, 101, 155));
        ManageCategories.setBackground(new Color(40, 101, 155));
        StockManagmentPanel.setBackground(new Color(40, 101, 155));
        StockManagment.setBackground(new Color(40, 101, 155));
        GoodsRecivedNotePanel.setBackground(new Color(40, 101, 155));
        GoodsRecivedNote.setBackground(new Color(40, 101, 155));
        CompanyRegPanel.setBackground(new Color(40, 101, 155));
        CompanyReg.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_GoodsReturnNoteActionPerformed

    private void SalaryManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryManagmentActionPerformed
        SalaryManagmentPanel.setBackground(new Color(23, 91, 150));
        SalaryManagment.setBackground(new Color(23, 91, 150));

        HomePanel.setBackground(new Color(40, 101, 155));
        Home.setBackground(new Color(40, 101, 155));
        ManageProductsPanel.setBackground(new Color(40, 101, 155));
        ManageProducts.setBackground(new Color(40, 101, 155));
        Order.setBackground(new Color(40, 101, 155));
        OrderPanel.setBackground(new Color(40, 101, 155));
        ManageUsersPanel.setBackground(new Color(40, 101, 155));
        ManageUsers.setBackground(new Color(40, 101, 155));
        GoodsReturnNotePanel.setBackground(new Color(40, 101, 155));
        GoodsReturnNote.setBackground(new Color(40, 101, 155));
        ManageCategoriesPanel.setBackground(new Color(40, 101, 155));
        ManageCategories.setBackground(new Color(40, 101, 155));
        StockManagmentPanel.setBackground(new Color(40, 101, 155));
        StockManagment.setBackground(new Color(40, 101, 155));
        GoodsRecivedNotePanel.setBackground(new Color(40, 101, 155));
        GoodsRecivedNote.setBackground(new Color(40, 101, 155));
        CompanyRegPanel.setBackground(new Color(40, 101, 155));
        CompanyReg.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_SalaryManagmentActionPerformed

    private void CompanyRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyRegActionPerformed
        loadPanel(new Test());
        
        CompanyRegPanel.setBackground(new Color(23, 91, 150));
        CompanyReg.setBackground(new Color(23, 91, 150));

        HomePanel.setBackground(new Color(40, 101, 155));
        Home.setBackground(new Color(40, 101, 155));
        ManageProductsPanel.setBackground(new Color(40, 101, 155));
        ManageProducts.setBackground(new Color(40, 101, 155));
        Order.setBackground(new Color(40, 101, 155));
        OrderPanel.setBackground(new Color(40, 101, 155));
        ManageUsersPanel.setBackground(new Color(40, 101, 155));
        ManageUsers.setBackground(new Color(40, 101, 155));
        GoodsReturnNotePanel.setBackground(new Color(40, 101, 155));
        GoodsReturnNote.setBackground(new Color(40, 101, 155));
        ManageCategoriesPanel.setBackground(new Color(40, 101, 155));
        ManageCategories.setBackground(new Color(40, 101, 155));
        StockManagmentPanel.setBackground(new Color(40, 101, 155));
        StockManagment.setBackground(new Color(40, 101, 155));
        GoodsRecivedNotePanel.setBackground(new Color(40, 101, 155));
        GoodsRecivedNote.setBackground(new Color(40, 101, 155));
        SalaryManagmentPanel.setBackground(new Color(40, 101, 155));
        SalaryManagment.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_CompanyRegActionPerformed

    private void sMButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMButton11ActionPerformed
        loadPanel(new profilePage());

        SalaryManagmentPanel.setBackground(new Color(40, 101, 155));
        SalaryManagment.setBackground(new Color(40, 101, 155));
        HomePanel.setBackground(new Color(40, 101, 155));
        Home.setBackground(new Color(40, 101, 155));
        ManageProductsPanel.setBackground(new Color(40, 101, 155));
        ManageProducts.setBackground(new Color(40, 101, 155));
        Order.setBackground(new Color(40, 101, 155));
        OrderPanel.setBackground(new Color(40, 101, 155));
        ManageUsersPanel.setBackground(new Color(40, 101, 155));
        ManageUsers.setBackground(new Color(40, 101, 155));
        GoodsReturnNotePanel.setBackground(new Color(40, 101, 155));
        GoodsReturnNote.setBackground(new Color(40, 101, 155));
        ManageCategoriesPanel.setBackground(new Color(40, 101, 155));
        ManageCategories.setBackground(new Color(40, 101, 155));
        StockManagmentPanel.setBackground(new Color(40, 101, 155));
        StockManagment.setBackground(new Color(40, 101, 155));
        GoodsRecivedNotePanel.setBackground(new Color(40, 101, 155));
        GoodsRecivedNote.setBackground(new Color(40, 101, 155));
        CompanyRegPanel.setBackground(new Color(40, 101, 155));
        CompanyReg.setBackground(new Color(40, 101, 155));
    }//GEN-LAST:event_sMButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompanyReg;
    private javax.swing.JPanel CompanyRegPanel;
    private javax.swing.JButton GoodsRecivedNote;
    private javax.swing.JPanel GoodsRecivedNotePanel;
    private javax.swing.JButton GoodsReturnNote;
    private javax.swing.JPanel GoodsReturnNotePanel;
    private javax.swing.JButton Home;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JButton ManageCategories;
    private javax.swing.JPanel ManageCategoriesPanel;
    private javax.swing.JButton ManageProducts;
    private javax.swing.JPanel ManageProductsPanel;
    private javax.swing.JButton ManageUsers;
    private javax.swing.JPanel ManageUsersPanel;
    private javax.swing.JButton Order;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JButton SalaryManagment;
    private javax.swing.JPanel SalaryManagmentPanel;
    private javax.swing.JButton StockManagment;
    private javax.swing.JPanel StockManagmentPanel;
    private com.stockmaster.assets.components.Background1 background11;
    private javax.swing.JPanel contentLoader;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private com.stockmaster.assets.components.SMButton1 sMButton11;
    private com.stockmaster.assets.components.SMSearch sMSearch1;
    // End of variables declaration//GEN-END:variables
}
